/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/eOMPU8itr1r
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Input } from "@/components/ui/input"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuGroup, DropdownMenuLabel, DropdownMenuItem, DropdownMenuSeparator } from "@/components/ui/dropdown-menu"
import { Button } from "@/components/ui/button"

export function SearchBarTwo() {
  return (
    <div className="flex items-center border rounded-md overflow-hidden">
      <Input
        type="text"
        placeholder="Doctor name, surname"
        className="border-none flex-1 focus:ring-0 focus:outline-none"
      />
      <span className="mx-2 text-gray-300">|</span>
      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <Button variant="outline" className="w-40 justify-start font-normal">
            Specialty
            <ChevronDownIcon className="ml-auto h-4 w-4 opacity-50" />
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent className="w-[200px]">
          <DropdownMenuGroup>
            <DropdownMenuLabel>Medical Specialties</DropdownMenuLabel>
            <DropdownMenuItem>Family Medicine</DropdownMenuItem>
            <DropdownMenuItem>Internal Medicine</DropdownMenuItem>
            <DropdownMenuItem>Pediatrics</DropdownMenuItem>
            <DropdownMenuItem>Obstetrics and Gynecology</DropdownMenuItem>
            <DropdownMenuItem>Surgery</DropdownMenuItem>
          </DropdownMenuGroup>
          <DropdownMenuSeparator />
          <DropdownMenuGroup>
            <DropdownMenuLabel>Surgical Specialties</DropdownMenuLabel>
            <DropdownMenuItem>Orthopedic Surgery</DropdownMenuItem>
            <DropdownMenuItem>Neurosurgery</DropdownMenuItem>
            <DropdownMenuItem>Cardiothoracic Surgery</DropdownMenuItem>
            <DropdownMenuItem>Plastic Surgery</DropdownMenuItem>
          </DropdownMenuGroup>
        </DropdownMenuContent>
      </DropdownMenu>
      <span className="mx-2 text-gray-300">|</span>
      <Input type="text" placeholder="Clinic" className="border-none flex-1 focus:ring-0 focus:outline-none" />
      <span className="mx-2 text-gray-300">|</span>
      <div className="flex items-center px-2">
        <MapPinIcon className="w-4 h-4 text-gray-700" />
        <Input type="text" placeholder="Location" className="border-none flex-1 focus:ring-0 focus:outline-none" />
      </div>
      <Button className="bg-[#f7931e] text-white rounded-none">
        <SearchIcon className="w-4 h-4" />
      </Button>
    </div>
  )
}

function ChevronDownIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  )
}


function MapPinIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z" />
      <circle cx="12" cy="10" r="3" />
    </svg>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}
